background {
    monitor =
    path = screenshot
    contrast = 1.0
    vibrancy = 0.5
    blur_passes = 4
    blur_size = 4
}

label {
	monitor =
	position = 0, 80
	halign = center
	valign = center

	text = $TIME
	color = rgb(255, 255, 255)
	font_size = 144
	font_family = Noto Sans
    shadow_passes = 2
    shadow_boost = 0.15
}

label {
    monitor =
    position = 0, -32
    halign = center
    valign = center

	text = cmd[update:1000] date "+%Y-%m-%d, %A, Week %V"
	color = rgb(255, 255, 255)
	font_size = 20
	font_family = Noto Sans
    shadow_passes = 2
    shadow_boost = 0.4
}

label {
    monitor =
    position = 0, -154
    halign = center
    valign = center

	text = $FAIL
	color = rgba(204, 34, 34, 1.0)
	font_size = 12
	font_family = Noto Sans
    shadow_passes = 2
    shadow_boost = 0.4
}

input-field {
    monitor =
    position = 0, -120
    halign = center
    valign = center
    size = 400, 32

    rounding = 8
    outline_thickness = 2
    inner_color = rgba(0, 0, 0, 0.15)
    outer_color = rgba(255, 255, 255, 1.0)
    font_color = rgba(255, 255, 255, 1.0)
    check_color = rgba(255, 255, 68, 1.0)
    fail_color = rgba(204, 34, 34, 1.0)
    fade_on_empty = false
    placeholder_text =
    fail_text =

    shadow_passes = 2
    shadow_boost = 0.4

    dots_size = 0.5
    dots_spacing = 0.2
    dots_center = false
    font_family = Noto Sans
}
