source = ~/.config/hypr/hyprland/variables.conf

bind = super, r, exec, uwsm app -- $app_launcher
bind = super, b, exec, uwsm app -- $browser
bind = super, t, exec, uwsm app -- $terminal
bind = super, f, exec, uwsm app -- $file_manager

input {
    kb_layout = se
}
