$terminal = kitty
$browser = firefox
$file_manager = thunar
$app_launcher = fuzzel

exec-once = uwsm app -- ags run --gtk4

bind = super ctrl shift alt, q, exec, uwsm stop  # TODO: replace with proper power menu
bind = super ctrl shift alt, l, exec, pidof hyprlock || hyprlock
bind = super ctrl shift alt, r, exec, ags quit; uwsm app -- ags run --gtk4

bind = super, t, exec, uwsm app -- $terminal
bind = super, b, exec, uwsm app -- $browser
bind = super, f, exec, uwsm app -- $file_manager
bind = super, r, exec, uwsm app -- $app_launcher

bind = super ctrl, c, killactive
bind = super ctrl, f, togglefloating
bind = super ctrl, p, pin
bind = super ctrl, s, swapsplit

bindm = super, mouse:272, movewindow
bindm = super, mouse:273, resizewindow

bind = super, up, movefocus, u
bind = super, right, movefocus, r
bind = super, down, movefocus, d
bind = super, left, movefocus, l

bind = super ctrl, up, swapwindow, u
bind = super ctrl, right, swapwindow, r
bind = super ctrl, down, swapwindow, d
bind = super ctrl, left, swapwindow, l

bind = super, 1, workspace, r~1
bind = super, 2, workspace, r~2
bind = super, 3, workspace, r~3
bind = super, 4, workspace, r~4
bind = super, 5, workspace, r~5
bind = super, 6, workspace, r~6
bind = super, 7, workspace, r~7
bind = super, 8, workspace, r~8
bind = super, 9, workspace, r~9
bind = super, 0, workspace, r~10

bind = super ctrl, 1, movetoworkspace, r~1
bind = super ctrl, 2, movetoworkspace, r~2
bind = super ctrl, 3, movetoworkspace, r~3
bind = super ctrl, 4, movetoworkspace, r~4
bind = super ctrl, 5, movetoworkspace, r~5
bind = super ctrl, 6, movetoworkspace, r~6
bind = super ctrl, 7, movetoworkspace, r~7
bind = super ctrl, 8, movetoworkspace, r~8
bind = super ctrl, 9, movetoworkspace, r~9
bind = super ctrl, 0, movetoworkspace, r~10

windowrulev2 = float, initialTitle:Picture-in-Picture
windowrulev2 = pin, initialTitle:Picture-in-Picture
windowrulev2 = size 480 270, initialTitle:Picture-in-Picture
windowrulev2 = keepaspectratio, initialTitle:Picture-in-Picture
windowrulev2 = nodim, initialTitle:Picture-in-Picture

layerrule = noanim, launcher # Resizing animation from fuzzel

general {
    border_size = 1
    col.active_border = rgb(f6ecc3)
    col.inactive_border = rgb(1d2021)
    gaps_in = 8
    gaps_out = 32
    layout = dwindle

    snap {
        enabled = true
    }
}

decoration {
    rounding = 8

    blur {
        enabled = true
        size = 8
        passes = 2
    }

    shadow {
        enabled = false
        range = 0
        sharp = true
        color = rgba(0, 0, 0, 0.4)
        offset = 4 7
    }
}

input {
    kb_layout = se
    repeat_rate = 35
    repeat_delay = 300
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
    enable_swallow = true
    swallow_regex = ^(kitty)$
}
